# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Periodic Media Group Dev Team
email: contact@periodicmedia.co
description: > # this means to ignore newlines until "baseurl:"
  The ideal behind-the-scenes division that deals with software and
  hardware in general. We want to help people create- and that's what
  keeps us going! Visit us at [periodicmedia.co](http://periodicmedia.co/ "periodicmedia.co").
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pmgdev.ga" # the base hostname & protocol for your site
twitter_username: periodicmedia
github_username:  periodicmediagroup

# Build settings
markdown: kramdown
